# SPDX-FileCopyrightText: Copyright © 2024 - 2025 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

# Software
"*.java":
  - "reuse annotate --license 'Apache-2.0' --copyright 'Caleb Cushing' --copyright-prefix spdx-string-symbol --merge-copyrights"
  - &prettier "prettier --cache --ignore-unknown --write"
# Build Scripts
"*.gradle.kts":
  - &mit "reuse annotate --license 'MIT' --copyright 'Caleb Cushing' --copyright-prefix spdx-string-symbol --merge-copyrights --skip-unrecognised"
  - ktlint --format
"Makefile":
  - *mit
"{.config/git/hooks/*,*.sh}":
  - "reuse annotate --license 'MIT' --copyright 'Caleb Cushing' --copyright-prefix spdx-string-symbol --merge-copyrights --style python"
  - *prettier
# Documentation
"*.{md,adoc}":
  - "reuse annotate --license 'CC-BY-NC-4.0' --copyright 'Caleb Cushing' --copyright-prefix spdx-string-symbol --merge-copyrights"
  - *prettier
# Trivial files
"*.{xml,yml,yaml,properties,toml,json5,js}":
  - &cc0 "reuse annotate --license 'CC0-1.0' --copyright 'Caleb Cushing' --copyright-prefix spdx-string-symbol --merge-copyrights"
  - *prettier
".{editorconfig,gitattributes,mailmap}":
  - *cc0
  - *prettier
".*ignore":
  - *cc0
  - *prettier
