# SPDX-FileCopyrightText: Copyright © 2024 - 2026 Caleb Cushing
#
# SPDX-License-Identifier: CC0-1.0

[versions]
ep = "2.+"
junit = "6.+"
plugin-convention = "0.+"

[libraries]
assertj = "org.assertj:assertj-core:3.+"
commons-io = "commons-io:commons-io:2.+"
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "ep" }
errorprone-nullaway = "com.uber.nullaway:nullaway:0.+"
jspecify = "org.jspecify:jspecify:1.+"
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-parameters = { module = "org.junit.jupiter:junit-jupiter-params" }
plugin-convention-checkstyle = { module = "com.xenoterracide.gradle.convention:checkstyle", version.ref = "plugin-convention" }
plugin-convention-coverage = { module = "com.xenoterracide.gradle.convention:coverage", version.ref = "plugin-convention" }
plugin-convention-publish = { module = "com.xenoterracide.gradle.convention:publish", version.ref = "plugin-convention" }
plugin-convention-spotbugs = { module = "com.xenoterracide.gradle.convention:spotbugs", version.ref = "plugin-convention" }
plugin-dependency-analysis = "com.autonomousapps:dependency-analysis-gradle-plugin:3.+"
plugin-errorprone = "net.ltgt.gradle:gradle-errorprone-plugin:5.+"
plugin-gradle-plugin-publish = "com.gradle.publish:plugin-publish-plugin:1.+"
plugin-spotbugs = { module = "com.github.spotbugs.snom:spotbugs-gradle-plugin", version = "6.+" }
spotbugs = "com.github.spotbugs:spotbugs:4.+"

[bundles]
compile = ["jspecify"]
ep = ["errorprone-core", "errorprone-nullaway"]
test-impl = ["junit-api", "assertj", "junit-parameters"]
test-runtime = ["junit-engine", "junit-launcher"]

[plugins]
dependency-analysis = { id = "com.autonomousapps.dependency-analysis" }
semver = { id = "com.xenoterracide.gradle.semver", version = "0.14.+" }
